version: '3.9'

services:

  #https://nodered.org/docs/getting-started/docker
  # nodered
  nodered:
    build: ./node-red
    environment:
      - TZ=Asia/Colombo
    ports:
      - "1880:1880"
    volumes:
      - node-red-data:/data
    networks:
      - iot-network

networks:
  iot-network: 
    driver: bridge

volumes:
  node-red-data:
