version: '3.8'

services:
  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    ports:
      - "1880:1880"
    environment:
      - NODE_RED_USERNAME=${NODE_RED_USERNAME}
      - NODE_RED_PASSWORD=${NODE_RED_PASSWORD}
    volumes:
      - ./node-red:/data
    restart: unless-stopped

volumes:
  nodered_data:
